### ISSUE TITLE
bruh broken scripts folder

### ISSUE THREAD

**Issue by TheDorNell8** [raphaelswrld/CrabGame#1]
so. if u open project in unity or in explorer all .cs scripts will be broken. example: ႞႞႙ႚႧႧႧႚႢႢ႙.cs 
u cant play with this bugs

**Comment by raphaelrc4** [comment]
The Source Code isnt game ready, anyway you can RE all scripts to make them build & playtest ready i suggest Frida or IDA Pro

**Comment by raphaelswrld** [comment]
https://frida.re
